### POST - register
POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json

{   
  "username":"aaaaaaaaaaaaa",
  "name":"a",
  "lastName": "a",
  "email": "a@a.pl",
  "password":"a"
}

### GET - confirm user
GET http://localhost:3000/api/users/confirm/121 HTTP/1.1

### POST - login
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{   
  "email": "c@c.pl",
  "password":"qwerty"
}

### GET - username
GET http://localhost:3000/api/users/a@a.pl HTTP/1.1
content-type: application/application/json  
